### ISSUE TITLE
V1.1.6 V2.0.0 V2.2.0 V2.2.2 Windows 7 is not supported

### ISSUE THREAD

**Issue by jianhuaz** [jakky1/video_player_win#11]
V1.1.6 V2.0.0 V2.2.0 V2.2.2 Windows 7 is not supported

**Comment by jakky1** [comment]
Please try to play a simple MP3 audio file.

If you can't play an MP3 audio file in Windows 7,
then this package not support Windows 7.
I have no Windows 7 to debug on it... :(

**Comment by jianhuaz** [comment]
When I try to start software：
The procedure entry point MFPutWaitingWorkItem could not be located in the dynamic link library MFPlat.DLL.
windows 7.

**Comment by jakky1** [comment]
Thanks for the information.

However, 
the related code is copy from Microsoft sample code,
and I cannot find a simple way to rewrite that,
and since Microsoft stop supporting Windows 7 after 2020/01,
so I won't try to fix it... :(
