### ISSUE TITLE
DirectShow support?

### ISSUE THREAD

**Issue by albrrt** [jakky1/video_player_win#12]
Hi @jakky1 many thanks for your package.

I am looking for a simple package to play HAP video files on Windows.

I understand your package only supports Media Foundation codecs. I'm no expert in video but I learned that [HAP requires DirectShow, even with K-Like codecs installed](https://codecs.forumotion.net/t4335-hap-support-not-working#22783). 

Would it be possible to add support for DirectShow?

Thank you

**Comment by jakky1** [comment]
No.
Directshow is deprecated since Vista (even though it still works on Windows 11 ...),
so this package will not support Directshow.

But, I think (not sure) Media foundation can use Directshow codec.
Maybe you can try it.
