### ISSUE TITLE
[crash] I encountered the following crash, is there any way to solve it?

### ISSUE THREAD

**Issue by yubnxd** [jakky1/video_player_win#19]
![image](https://github.com/jakky1/video_player_win/assets/103245603/e15c25ed-c7fd-464e-af60-e43c73cad85d)

**Comment by jakky1** [comment]
What did you do before crash ? ( ex. After close player ? )
Did it 100% always occurs?
Did it crash when you play other videos ? 
Or it only crash on certain video file ?

**Comment by yubnxd** [comment]
Yes, It crashed after close video player.

It not 100% occurs.

Not sure if it will crash when play other videos.

And i’am not change the code of plugin.

I try searched  `MFPlat.dll` , it seems is the Microsoft system MediaKit.  And there was some log collected by Analytics tool in the below screenshot, and some suggested solutions by AI, I don’t know if it is useful.

<img width="1215" alt="截屏2023-10-16 上午10 20 11" src="https://github.com/jakky1/video_player_win/assets/103245603/f86084e1-6ec8-465f-9241-3e0f4cbf77e7">

<img width="1223" alt="截屏2023-10-16 上午10 20 47" src="https://github.com/jakky1/video_player_win/assets/103245603/26f543c6-f694-4189-a3b4-002d1eb46f33">

**Comment by jakky1** [comment]
Thanks for reporting this crash issue.
There is really something wrong in this package.

I tried to fix this issue,
and it seems work so far.

Please give it a try with new version on github,
and let me know if crash still occurs:
```
dependencies:
  video_player_win:
    git:
      url: https://github.com/jakky1/video_player_win.git
      ref: master
```

**Comment by yubnxd** [comment]
> Thanks for reporting this crash issue. There is really something wrong in this package.
> 
> I tried to fix this issue, and it seems work so far.
> 
> Please give it a try with new version on github, and let me know if crash still occurs:
> 
> ```
> dependencies:
>   video_player_win:
>     git:
>       url: https://github.com/jakky1/video_player_win.git
>       ref: master
> ```

Thanks for your support. I need to use the latest code to publish online to view the data collected by the crash collection tool. I will give you feedback once I get the results.

**Comment by yubnxd** [comment]
First of all, thank you for your support. No crash records have been received so far. I will continue to track this issue for a while and give feedback again.

But I encountered a new problem. When the video playback was completed, the value of `controller.value.position` I obtained was **0:00:00.000000**, so that the video playback completion event could not be captured at the code level. The following is my example code to obtain video position. any suggestions? Thanks!

```
void onPlaybackEvent() {
	final value = controller.value;
        final isComplete = value.position == value.duration;
        // do something when video playback was completed
}
controller.addListener(onPlaybackEvent);
```

**Comment by jakky1** [comment]
About detecting whether player is completed,
I fixed it and push a patch to github.

Please pull the new code again, 
and listen `controller.value.isCompleted` instead.

If it not works, or for futher discussion about this topic,
please open a new issue to tracking it.
I'd like to make this issue tracking crash problem only.

**Comment by yubnxd** [comment]
No record of crash found again, I think this problem has been fixed
