### ISSUE TITLE
application cant run

### ISSUE THREAD

**Issue by diegotus** [jakky1/video_player_win#2]
i created a clean project and just install the player. nothing else. and when i run it it give me those problem:
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: The command "setlocal [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: ..\..\nuget.exe install Microsoft.Windows.ImplementationLibrary -Version 1.0.220914.1 -ExcludeVersion -OutputDirectory C:/developement/myProject/testfr/build/windows/packages [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmEnd [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmErrorLevel [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: exit /b %1 [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmDone [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd" exited with code 1. [C:\developement\myProject\testfr\build\windows\plugins\video_player_win\video_player_win_DEPENDENCIES_DOWNLOAD.vcxproj]
Exception: Build process failed.
Exited (sigterm)

but everthing is ok whith flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

please help

**Comment by jakky1** [comment]
I guess you may also have the same problem building other packages which also use "nuget" to download VS library,
such as package [webview_windows].

I had encounter the same error several months ago.
But... I forgot how I fixed it...
It is a huge work for me to re-install all the environment (Windows 10 / VS2022 / flutter / etc...) to duplicate this error message,
So I'm sorry I cannot give you the answer now :(

You can google "MSB3073" for solution, but it is a little hard to find the correct solution for you.
However I google it and list below:
- delete the %appdata%\nuget\nuget.config file
- run Visual studio in [Administrator] mode, and try to build something
- run "flutter build ." in command line in [Administrator] mode
- move you project directory to drive D/E or any other folder that is writable without Administrator permission

It would be appreciated if you post the solution you found after you solve it :)

**Comment by diegotus** [comment]
> 

thank you so much! i followed you steps till the 3rd ont(run "flutter build"....) and it works well. thank you so much for your help

**Comment by jakky1** [comment]
Thanks for your response :)
