### ISSUE TITLE
[crash] load http hls url is crash

### ISSUE THREAD

**Issue by ANC1024GO** [jakky1/video_player_win#20]
### log: 
```
[video_player_win] native: path = <>
lost connection device.
```

### version:
```
video_player: ^2.7.0
video_player_win: ^2.3.4
```

### using code: 
```
VideoPlayerController.networkUrl('https.xx.xx.m3u8');
```
### format: 
```
HLS H.265
```

**Comment by jakky1** [comment]
duplicate to #5 
this package doesn't support HLS (m3u8)

**Comment by ANC1024GO** [comment]
> duplicate to #8 this package doesn't support HLS (m3u8)
> 
> You can try another package 'media_kit' instead.

Thanks , 'media_kit' seeking in HLS stream loads all intermediate .ts segments, [](https://github.com/media-kit/media-kit/issues/395)

**Comment by jakky1** [comment]
@ANC1024GO,

Now can play .m3u8 url with new version 3.0.0.
Please give it a try ~
