### ISSUE TITLE
App crashed during initializing networkUrl

### ISSUE THREAD

**Issue by GideonKock** [jakky1/video_player_win#21]
I try to stream a camera view from a local camera. I get the following info:

```
video_player_win] native: path = <https://...@127.0.0.1:55756/Acs/Streaming/Video/Live/Mp4/%3Fcamera=18081_f01a4296-7683-4247-9c27-4e540d0dac7d&quality=medium&audio=0>
[native] ~MyPlayer()
[log] [video_player_win] controller intialize (open video) failed
[log] video file load failed
Lost connection to device.
Exited (sigterm)
```

**Comment by jakky1** [comment]
Please provide more details,
or tell me how to test on it.

ex. Give me an url that cannot play by this package, and make sure I can access it so I can debug for it.

**Comment by jakky1** [comment]
I have no local camera, so I cannot test on it.
( Even if I have, different camera manufacturer may have different solution, so may not have the same result )

If you can play any other network url,
that means K-lite codec doesn't support the codec your camera using,
or there maybe some network issue in your evironment.

Anyway if I have no the same camera device then I cannot do anything on it...

**Comment by jakky1** [comment]
However,
you can try to copy the url in the log,
and paste it onto browser.

If browser also cannot play it,
maybe there are some problem in the url.
I notice that there are some url-encoded chars (ex. %3F),
maybe the url-encoded chars cause the problem.

**Comment by jakky1** [comment]
It looks like a live streaming.
This package doesn't support live streaming playback.
I have no plan to support it.
