### ISSUE TITLE
nuget.exe failed

### ISSUE THREAD

**Issue by qiuguian** [jakky1/video_player_win#22]
CMake Error at flutter/ephemeral/.plugin_symlinks/video_player_win/windows/CMakeLists.txt:35 (message):
  Integrity check for
  D:/workspace/app/build/windows/x64/nuget.exe failed

**Comment by jakky1** [comment]
I tried to clean build this package and it works well today.

Could you run `flutter clean` first, and build again?
If it is still failed, please let me know which version of `video_player_win` you are using.

**Comment by qiuguian** [comment]
video_player_win version is 2.3.4  and flutter doctor is
![7551701068969_ pic](https://github.com/jakky1/video_player_win/assets/7962840/f4da1664-e172-4fe3-b590-4b83c5408142)
![7541701068893_ pic](https://github.com/jakky1/video_player_win/assets/7962840/caee6b54-f2ac-4295-88b5-7265d1445db6)
![7561701069113_ pic](https://github.com/jakky1/video_player_win/assets/7962840/ebc4d803-a851-41ff-b4bf-7e63ac46113e)

**Comment by qiuguian** [comment]
I had tried, still fails

**Comment by jakky1** [comment]
Please  open browser and download `https://dist.nuget.org/win-x86-commandline/v5.10.0/nuget.exe`.
Open console, cd to download path, and run `certutil -hashfile nuget.exe sha256`
If the result of sha256 string not equal to `852b71cc8c8c2d40d09ea49d321ff56fd2397b9d6ea9f96e532530307bbbafd3`
then there maybe something wrong with your ISP.

```
E:\Downloads> certutil -hashfile nuget.exe sha256
SHA256 的 nuget.exe 雜湊:
852b71cc8c8c2d40d09ea49d321ff56fd2397b9d6ea9f96e532530307bbbafd3
CertUtil: -hashfile 命令成功完成。
```

**Comment by qiuguian** [comment]
Thank you, I guess is proxy,  I try to use global vpn and it work
