### ISSUE TITLE
onErrorBuilder request

### ISSUE THREAD

**Issue by explorer-source** [jakky1/video_player_win#24]
While playing the network video, my app caches the video in `temp dir` so that the next time the user enters, it plays from the cache. When the user interrupts the download of the mp4 while it is not fully completed, it appears to crash without any error message. Is it possible to check for errors before playing so that I can play from the network instead or maybe just show error image?

**Comment by jakky1** [comment]
As mentioned in README, you can detect is there something wrong when calling `controller.initialize()`
```
  controller.initialize().then((value) {
    if (controller.value.isInitialized) {
      controller.play();
      setState(() {});
    } else {
      log("video file load failed");
    }
  });
```

You can also detect error during playing by `controller.value.errorDescription != null`

**Comment by explorer-source** [comment]
```dart
if (fileExists) {
        videoController = WinVideoPlayerController.file(file);
      } else {
        videoController = WinVideoPlayerController.network(wholeUrl);
      }

      videoController.initialize().then((value) {
        if (videoController.value.isInitialized) {
          videoController.play();
          videoController.setLooping(true);
          videoLoaded = true;
          setState(() {});
        } else {
          print('video load failed');
        }
      });
```
isInitialized is not sufficient because I'm showing `CircularProgressIndicator` till `videoLoaded` becomes `true` yet it crashes
```dart
  return videoLoaded
          ? Center(
              child: Texture(
                textureId: videoController.textureId_,
                filterQuality: FilterQuality.medium,
              ),
            )
          : const Center(child: CircularProgressIndicator());
```

**Comment by jakky1** [comment]
Could you give me a sample code that can reproduce this issue, including how you download file.
This sample code should be as simple as possible, and remove all irrelevant code.

**Comment by explorer-source** [comment]
Ohh I found the problem, missing extension is the reason. I removed the extension from the file when saving to file so it doesn't show up as video in File explorer immediately for "security" reasons. You can change file from `GxDhHlCNuO.mp4` to `GxDhHlCNuO` it crashes.
