### ISSUE TITLE
Consider merge this into VideoPlayer?

### ISSUE THREAD

**Issue by lucasjinreal** [jakky1/video_player_win#26]
So that users don't need deal with windows separately.

**Comment by jakky1** [comment]
I have no plan to do it.

For users who want to show video in windows,
just add 2 lines ONLY:
1. add `video_player_win: ^2.0.0` into `pubspec.yaml`
2. add code `WindowsVideoPlayer.registerWith();` before create video player,

Then users can use official `video_player` API to play video in windows.
They don't need write different code for windows video playing.
I think it is simple enough for now.

**Comment by at15** [comment]
There is now an open PR for windows support 

- https://github.com/flutter/packages/pull/5884
- https://github.com/flutter/flutter/issues/37673

**Comment by stuartmorgan** [comment]
> 2\. add code `WindowsVideoPlayer.registerWith();` before create video player

Are you not seeing the `flutter` tooling call this in the generated plugin registrant as a result of step 1? A federated implementation should not require manual registration.

**Comment by jakky1** [comment]
@stuartmorgan You're right. It's better without manual registration.
However, I have no time to read a lot of docs and following rules to merge into official package.

In addition, 
this package has some problems that I have no time and ability to fix them,
and the coding style not good enough.
And there are already someone working on Windows implementation of official `video_player` package.
These are also why I don't want to merge.

Anyone who wants to merge this package are welcome.

**Comment by jakky1** [comment]
Thanks @stuartmorgan mentioned in #30,
the call to `WindowsVideoPlayer.registerWith()` is not necessary, and removed from README now.

@lucasjinreal sorry for the wrong information.
There is no need to call `WindowsVideoPlayer.registerWith()`.
The only thing you need to do is add `video_player_win: ^2.0.0` into `pubspec.yaml`.
