### ISSUE TITLE
Can't play certain .mp4 files

### ISSUE THREAD

**Issue by khoadng** [jakky1/video_player_win#3]
The video looks distorted when using this plugin.
WMP can play it without problems so I don't know what is wrong.

[link](https://user-images.githubusercontent.com/19619099/212602608-efa2bde2-ed8a-4d60-b28d-8b50a5e4bf9b.mp4)

**Comment by jakky1** [comment]
Any video with width or height that is not a multiples of 16 may cause video skew,
and I didn't handle this case before.

Now Fixed.
Please try the lastest version ``video_player_win: ^1.1.5 ``

**Comment by khoadng** [comment]
It is working yay. Thanks for the quick response.
