### ISSUE TITLE
README instructs clients to add unnecessary manual registration code

### ISSUE THREAD

**Issue by stuartmorgan** [jakky1/video_player_win#30]
[This step in the README](https://github.com/jakky1/video_player_win?tab=readme-ov-file#register-player-first) should not be necessary (and in my quick test locally, it worked without it as I expected); because of [this pubspec line](https://github.com/jakky1/video_player_win/blob/d2d512b2fb16675e24c7e8bb2d72bb488cd09401/pubspec.yaml#L40), anyone adding a dependency on `video_player_win` is indicating to the `flutter` tool that they want to use this federated implementation, so a call to `WindowsVideoPlayer.registerWith();` will be generated during the build.

**Comment by jakky1** [comment]
Thanks for reminding.

I thought the `registerWith()` will not be called if official `video_player` not add my package into `default_package: video_player_win`.
Now I find this is my misunderstanding.

The README is uploaded to github & pub.dev.
