### ISSUE TITLE
setPlaybackSpeed Issue

### ISSUE THREAD

**Issue by NavidFarahmandian** [jakky1/video_player_win#31]
` _controller.setPlaybackSpeed(items[index]).then((_) {
                                print("Playback speed set to ${items[index]}");
                              });`
                              
                              it's not working, items are     List<double> items = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0];

**Comment by jakky1** [comment]
Fix. Please try new version `2.3.6`
