### ISSUE TITLE
During initialization, invalid video links or network disconnections can cause crashes

### ISSUE THREAD

**Issue by jinpang** [jakky1/video_player_win#36]
Provide an invalid video address (empty string or a non-existent URL address) or disconnect from the network, which will crash during initialization

Launching lib\main.dart on Windows in debug mode...
Building Windows application...
√  Built build\windows\x64\runner\Debug\video_player_win_example.exe.
Debug service listening on ws://127.0.0.1:3230/cuDVVJ-LYFw=/ws
Syncing files to device Windows...
HandleMethodCall: openVideo
[video_player_win] isOpenVideo: 1
[video_player_win] path: https://files.acadsoc.com.cn/iesfiles/TempVideo/20230625/0f106ae4-301f-4027-a70f-edcc132d1001q.mp4
[video_player_win] convResult: 99
[video_player_win]: textureId=2129078886064
[video_player_win]: OpenURL end:0
[video_player_win]: OpenURL isSuccess =0
[native] ~MyPlayer()
Lost connection to device.

**Comment by Andrekarma** [comment]
Hi @jakky1 , i think that the player should be able to open video files that have no common extension. 
For example i receive the error "controller intialize (open video) failed" when passing an mp4 file with .phv extension

**Comment by jakky1** [comment]
About file extension, I have no idea how to solve it. So I won't fix it.

If crash no longer occurs, I will close this issue.

**Comment by jakky1** [comment]
@Andrekarma
About file extension, I have no idea how to solve it. So I won't fix it.
And please open a NEW issue if your question is not related to current issue.
