### ISSUE TITLE
App not able to open after including this package: MF.dll not found

### ISSUE THREAD

**Issue by joeljoy** [jakky1/video_player_win#37]
After installation, when trying to open it, it shows the following error: 
![Screenshot 2024-06-12 at 4 38 55 PM (2)](https://github.com/jakky1/video_player_win/assets/8502660/463e3d76-7b3b-4840-b75d-19fb96f43a84)

Is there any way to check if the media package is available and handle graciously?

**Comment by jakky1** [comment]
This is not a general case. There maybe something wrong with your PC.

https://steamcommunity.com/app/629520/discussions/0/5671690972169897616/?l=japanese

Please refer to the link above,
it seems that you should download "Media Feature Pack" from Microsoft website.

https://www.microsoft.com/en-in/download/details.aspx?id=48231
