### ISSUE TITLE
Player background

### ISSUE THREAD

**Issue by zakiroof** [jakky1/video_player_win#40]
The player has a black background. Apparently, line 324 is responsible for this. Is there a way to override this somehow? Black color doesnt fit into our design.

https://github.com/jakky1/video_player_win/blob/b807019755f0340dc57b79b0d34a90fe4621ab09/lib/video_player_win.dart#L321-L334

**Comment by jakky1** [comment]
Fixed.

Please try the new version `2.3.10`

**Comment by zakiroof** [comment]
It works like a charm. Thanks for fixing
