### ISSUE TITLE
Does not work when the system is not connected to any audio output devices

### ISSUE THREAD

**Issue by czw299** [jakky1/video_player_win#41]
I reproduced the problem on two Windows 10/11 desktops, plugged in the 3.5mm speaker, and it worked fine. Once removed, the video stopped playing immediately.

The system seems to have to have an audio output device, whether it's a speaker, a headset, or a display connected by HDMI or DP that acts as an audio output device.

**Comment by czw299** [comment]
Oh, My flutter SDK is 3.19.6, and use video_player_win 2.3.9

**Comment by jakky1** [comment]
Fixed.
Please try the new version `2.3.11`

**Comment by czw299** [comment]
> Fixed. Please try the new version `2.3.11`

So quickly! Appreciated
