### ISSUE TITLE
Does 3.0.0 work on Windows 10 ?

### ISSUE THREAD

**Issue by czw299** [jakky1/video_player_win#43]
I tested it fine on Windows 11, and after installing Windows 10 22H2(19045.2846) on the same computer, it crashed.
The crash may have been caused by ucrtbase.dll. I'm not sure. Maybe need some dll?

**Comment by jakky1** [comment]
Version 3.0.0 should be able to run normally on windows 8 or above.

I only tested it on Windows 11.

From what you said, it seems that this package does not currently work properly on win10.

But, I have no win10 PC to debug on it...:(

HELP WANTED!
I hope someone can help me solve the problem of this package crashing in win10 !!!

**Comment by jakky1** [comment]
After some study,
this dll file is part of "Microsoft Visual C++ Redistributable".

Could you try to install "Microsoft Visual C++ Redistributable" and test again ?

**Comment by czw299** [comment]
> After some study, this dll file is part of "Microsoft Visual C++ Redistributable".
> 
> Could you try to install "Microsoft Visual C++ Redistributable" and test again ?

I tried it and it didn't work. I'll try to debug on Windows 10 later.

**Comment by jakky1** [comment]
Thanks for help.
I think it maybe caused by string copy operation in the end of OpenURL() function, which may need ucrtbase.dll file.

**Comment by czw299** [comment]
> Thanks for help. I think it maybe caused by string copy operation in the end of OpenURL() function, which may need ucrtbase.dll file.

I found this!
![img_v3_02fj_58c30473-4c96-44d6-9956-e8373f7ea7eg](https://github.com/user-attachments/assets/da802e96-acc2-4ab7-a67d-a8060baddde0)

**Comment by czw299** [comment]
> Thanks for help. I think it maybe caused by string copy operation in the end of OpenURL() function, which may need ucrtbase.dll file.

I'm not very good at C++, try my best and find this. This is debug in WMware Virtual machine.
![20241012-184957](https://github.com/user-attachments/assets/48278bd3-4f77-4d2f-b93a-59da3dfb32aa)

**Comment by jakky1** [comment]
I push a patch onto github.
Please try in on your Windows 10 and let me know if it still crash.

```yaml
dependencies:
  video_player_win:
    git:
      url: https://github.com/jakky1/video_player_win.git
      ref: master
```

**Comment by czw299** [comment]
> I push a patch onto github. Please try in on your Windows 10 and let me know if it still crash.
> 
> Remember modify your pubspec.yaml:
> 
> ```yaml
> dependencies:
>   video_player_win:
>     git:
>       url: https://github.com/jakky1/video_player_win.git
>       ref: master
> ```

Still crash. Remove some code as shown in the image, and it works. But the video won't play
![image](https://github.com/user-attachments/assets/5409f99b-5a9d-4a74-a943-a66a614429bd)

**Comment by czw299** [comment]
![屏幕截图 2024-10-12 205238](https://github.com/user-attachments/assets/ffa0e005-c4af-4487-b620-fb0b67eac550)

**Comment by czw299** [comment]
![image](https://github.com/user-attachments/assets/359c1cad-e1b5-4349-a342-95d5426a946a)

😂😂😂Ohhhhhhhhhhhhhhhhhhhh, it works.

**Comment by jakky1** [comment]
@czw299 ,
Good Job :)

It seems that it crash on PC that without DirectX 12... :(

I modify the source code according to your comment,
and push a new version `3.1.0` to pub.dev.

Could you please help try it on your Windows 10 again? Thanks.
```yaml
dependencies:
  video_player_win: ^3.1.0
```

**Comment by czw299** [comment]
3.1.0 Works fine. Thanks😊
