### ISSUE TITLE
Not able to play .m3u8 videos through network

### ISSUE THREAD

**Issue by xdenzer** [jakky1/video_player_win#5]
I tried to play .m3u8 files directly from the network. It doesn't seem to work. It throws video error.

I tried installing all the k-lite codecs still there is the same issue. But the .m3u8 files are working fine on mobile devices with  the native video_player plugin.

**Comment by jakky1** [comment]
Unfortunately, K-lite codecs seems not support .m3u8 HLS protocol,
There are currently no plans to support this feature.

**Comment by jakky1** [comment]
@xdenzer,

Now can play .m3u8 url with new version `3.0.0`.
Please give it a try ~
